### PR TITLE
Work around Mac OSX missing nvidia-smi

### LINKED ISSUE #83: CUDArt should not rely on `nvidia-smi` or `nvml` on Mac OSX
This is on master for CUDArt:

```
julia> versioninfo()
Julia Version 0.6.0-pre.beta.437
Commit 552626cc97 (2017-04-30 05:06 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.5.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libgfortblas
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)


julia> Pkg.build("CUDArt")
INFO: Building CUDAdrv
INFO: CUDAdrv.jl has already been built for this CUDA library, no need to rebuild.
INFO: Building CUDArt
WARNING: NVML not found, resorting to nvidia-smi
===============================[ ERROR: CUDArt ]================================

LoadError: could not spawn `nvidia-smi`: no such file or directory (ENOENT)
while loading /Users/solver/.julia/v0.6/CUDArt/deps/build.jl, in expression starting on line 366

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: CUDArt had build errors.

 - packages with build errors remain installed in /Users/solver/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("CUDArt")`
 - build a single package by running its `deps/build.jl` script

================================================================================

```

### PR DESCRIPTION
**Pull request by vchuravy**
Supersedes #84 and fixes #83.

@dlfivefifty, can you give this a go? I had to disable a feature but it should make CUDArt usable in situations where nvidia-smi is not available.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Still broken it looks like:
```julia
julia> Pkg.build("CUDArt")
INFO: Building CUDAdrv
INFO: CUDAdrv.jl has already been built for this CUDA library, no need to rebuild.
INFO: Building CUDArt
WARNING: NVML not found, resorting to nvidia-smi
WARNING: Encountered could not spawn `nvidia-smi`: no such file or directory (ENOENT) while executing `nvidia-smi`
===============================[ ERROR: CUDArt ]================================

LoadError: NVML nor nvidia-smi can be found.
while loading /Users/solver/.julia/v0.6/CUDArt/deps/build.jl, in expression starting on line 372
```

**Comment by vchuravy** [comment]
ah yes of course. Should be "fixed" now.

**Comment by dlfivefifty** [comment]
Now I get:
```julia
LoadError: Could not find a suitable host compiler (your CUDA v8.0.0 needs GCC <= 5.3.1).
while loading /Users/solver/.julia/v0.6/CUDArt/deps/build.jl, in expression starting on line 376
```
I'm not sure how to tell it to use the Homebrew gcc in `/usr/local/bin/gcc-7`

File: src/device.jl [hunk 1]
```diff
@@ -103,6 +103,14 @@ function filter_free(devlist)
         end
         ccall(("nvmlShutdown", libnvml), UInt32, ())
         return freelist
+    elseif isempty(nvidia_smi)
+        Base.warn_once(
+        """
+        Neither NVML nor nvidia-smi are available.
+        Please check your setup and install either one.
+        `CUDArt.filter_free` will not work.
```
Comment (musm) [inline src/device.jl]: Shouldn't this check also include isempty nvidiasmi

Comment (vchuravy) [inline src/device.jl]: I am not sure what you mean? This explicitly checks  `nvidia_smi`

**Comment by vchuravy** [comment]
@dlfivefifty CUDA is not supporting GCC7 as the error message tells you you will need GCC < 5.3  on your PATH. Normally that binary is called `gcc-49` or `gcc-53`.

**Comment by dlfivefifty** [comment]
OK installed gcc48 and now get:
```julia
nvcc fatal   : GNU C/C++ compiler is no longer supported as a host compiler on Mac OS X.
===============================[ ERROR: CUDArt ]================================

LoadError: failed process: Process(`/usr/local/cuda/bin/nvcc --compiler-bindir /usr/local/bin/gcc-4.8 --gpu-architecture sm_30 --shared wrapcuda.c -o libwrapcuda.dylib`, ProcessExited(1)) [1]
while loading /Users/solver/.julia/v0.6/CUDArt/deps/build.jl, in expression starting on line 376
```

**Comment by vchuravy** [comment]
@dlfivefifty Thanks for testing that and for sticking with this issue.
Can you post the output of `nvcc --verision`, and `which clang`?

**Comment by dlfivefifty** [comment]
[Macintosh-3:~] solver% /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:46_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
[Macintosh-3:~] solver% which clang
/usr/bin/clang

**Comment by vchuravy** [comment]
Thanks! Just added another commit.

**Comment by dlfivefifty** [comment]
```
nvcc fatal   : The version ('80100') of the host compiler ('Apple clang') is not supported
===============================[ ERROR: CUDArt ]================================

LoadError: failed process: Process(`/usr/local/cuda/bin/nvcc --compiler-bindir /usr/bin/clang --gpu-architecture sm_30 --shared wrapcuda.c -o libwrapcuda.dylib`, ProcessExited(1)) [1]
while loading /Users/solver/.julia/v0.6/CUDArt/deps/build.jl, in expression starting on line 380
```

**Comment by vchuravy** [comment]
... oh the joys of walled gardens.

The error method says it all. Your current clang compiler version is incompatible with your version of CUDA 8, see https://github.com/arrayfire/arrayfire/issues/1384
You should be able to downgrade your version of clang, but my wisdom is at an end here.

File: src/device.jl (hunk 1 above)
Comment (musm) [inline src/device.jl]:
```julia
 if !isempty(libnvml)
        ccall(("nvmlInit", libnvml), UInt32, ())
        freelist = Int[]
        for i in devlist
            devref = Ref{Ptr{Void}}(0)
            ccall(("nvmlDeviceGetHandleByIndex", libnvml),
                  UInt32, (UInt32, Ptr{Void}), i, devref)
            status = ccall(("nvmlDeviceGetComputeRunningProcesses", libnvml),
                           UInt32, (Ptr{Void}, UInt32, Ptr{Void}),
                           devref, Ref{UInt32}(0), C_NULL)
            if status == 0
                push!(freelist, i)
            end
        end
        ccall(("nvmlShutdown", libnvml), UInt32, ())
        return freelist
    elseif !isempty(nvidia_smi)
        smi = readstring(`$nvidia_smi`)
        if contains(smi, "No running")
            return devlist
        end
        idx = search(smi, r"[Pp]rocesses:")
        isempty(idx) && error("Neither search string found")
        lines = split(smi[last(idx):end], '\n')
        freeset = Set(devlist)
        for line in lines
            m = match(r"^\| +([0-9]+)", line)
            if m !== nothing
                length(m.captures) == 1 || error("Expected only a single capture")
                dev = parse(Int, m.captures[1])
                delete!(freeset, dev)
            end
        else
    else
        Base.warn_once(
        """
        Neither NVML nor nvidia-smi are available.
        Please check your setup and install either one.
        `CUDArt.filter_free` will not work.
        """)
        return devlist
     end

```

Comment (vchuravy) [inline src/device.jl]: Ah you mean reorder the if-clause. Yeah it's probably clearer to have the predicates in the other order but that won't change the semantics. Will change that tomorrow.

**Comment by dlfivefifty** [comment]
It built!  I followed the following directions from the link:
```julia
1. Log in to https://developer.apple.com/downloads/
2. Download Xcode CLT (Command Line Tools) 8.2
3. Install CLT
`Run sudo xcode-select --switch /Library/Developer/CommandLineTools`
4. Verify that clang has been downgraded via clang --version
```

**Comment by vchuravy** [comment]
perfect thanks! I will think about how to fix that.

**Comment by vchuravy** [comment]
CUDAnative should actually do even better. Can you report the test failures?

**Comment by vchuravy** [comment]
I tested this locally by removing the nvml and nvidia-smi releated entries from my `build/ext.jl". So I am in good hopes that this will work!
